name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  NODE_ENV: production
  CI: true
  VITE_BASE_URL: /

jobs:
  deploy:
    if: ${{ github.repository == 'mike7seven/mike7seven.github.io' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout React Slides repo
        uses: actions/checkout@v4
        with:
          repository: mike7seven/react-slides
          token: ${{ secrets.GH_PAT }}
          path: react-slides

      - name: Copy content file
        run: cp content.md react-slides/public/
          
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: react-slides/package-lock.json

      - name: Install dependencies
        working-directory: react-slides
        run: npm ci

      - name: Build
        working-directory: react-slides
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: 'react-slides/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 