name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: production
  CI: true
  VITE_BASE_URL: /

jobs:
  build-and-test:
    if: ${{ github.repository == 'mike7seven/mike7seven.github.io' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v4

      - name: Checkout React Slides repo
        uses: actions/checkout@v4
        with:
          repository: mike7seven/react-slides
          token: ${{ secrets.GH_PAT }}
          path: react-slides
          fetch-depth: 0

      - name: Copy content file
        run: |
          cp mike7seven.github.io/content.md react-slides/public/
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: react-slides/package-lock.json

      - name: Install dependencies
        working-directory: react-slides
        run: |
          pwd
          ls -la
          npm ci
        continue-on-error: false

      - name: Build
        working-directory: react-slides
        run: |
          npx vite build
        continue-on-error: false
