name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: production
  CI: true

jobs:
  build-and-test:
    if: ${{ github.repository == 'mike7seven/mike7seven.github.io' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v4
        with:
          path: pages-content

      - name: Checkout React Slides repo
        uses: actions/checkout@v4
        with:
          repository: mike7seven/react-slides
          token: ${{ secrets.GH_PAT }}
          path: react-slides
          fetch-depth: 0

      - name: Copy content file
        run: |
          cp pages-content/content.md react-slides/public/
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: react-slides/package-lock.json

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('react-slides/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: react-slides
        continue-on-error: false

      - name: Test
        run: npm test
        working-directory: react-slides
        continue-on-error: false

      - name: Build
        run: npm run build
        working-directory: react-slides
        continue-on-error: false
