name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_ENV: production
  CI: true

jobs:
  build:
    if: ${{ github.repository == 'mike7seven/mike7seven.github.io' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v4
        with:
          path: pages-content
          
      - name: Checkout React Slides repo
        uses: actions/checkout@v4
        with:
          repository: mike7seven/react-slides
          token: ${{ secrets.GH_PAT }}
          path: react-slides

      - name: Copy content file
        run: |
          cp pages-content/content.md react-slides/public/
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: react-slides/package-lock.json

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('react-slides/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: react-slides
        continue-on-error: false

      - name: Build
        run: npm run build
        working-directory: react-slides
        continue-on-error: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: react-slides/dist
          retention-days: 7

  deploy:
    if: ${{ github.repository == 'mike7seven/mike7seven.github.io' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 